"""Generate Witness.lean: self-contained Lean 4 file (no imports) defining
stable matchings concretely and proving the 16-matching witness by kernel
computation. Rank tables are derived from the SAT-found instance and
cross-checked against smp.py before emission."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))  # repo root: smp.py
from smp import count_stable, ranks

mpref = [(1, 2, 0, 4, 3), (4, 0, 3, 1, 2), (3, 4, 0, 2, 1), (2, 1, 3, 4, 0), (0, 4, 1, 2, 3)]
wpref = [(3, 0, 2, 1, 4), (2, 1, 4, 3, 0), (1, 2, 0, 4, 3), (4, 0, 1, 2, 3), (0, 3, 4, 2, 1)]

assert count_stable(mpref, wpref) == 16
mrank, wrank = ranks(mpref), ranks(wpref)

def tbl(t):
    return "[" + ", ".join("[" + ", ".join(map(str, row)) + "]" for row in t) + "]"

lean = f"""/-!
The 5x5 stable-marriage instance found by SAT (see ../encode.py) has
exactly 16 stable matchings, verified here by Lean's kernel alone
(`decide`, no imports, no native code).

Rank tables: `mrank[m][w]` = position of woman w in man m's list (0 = most
preferred); `wrank[w][m]` symmetric. Generated by gen_witness.py from the
instance recorded in f5/paper/f5.tex and cross-checked against smp.py.
-/

def mrank : List (List Nat) := {tbl(mrank)}
def wrank : List (List Nat) := {tbl(wrank)}

def get2 (t : List (List Nat)) (i j : Nat) : Nat :=
  ((t.getD i []).getD j 0)

/-- All permutations of a list (each as `mu` with `mu[m]` = partner of m). -/
def insertAll (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (insertAll x ys).map (y :: ·)

def permsOf : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (permsOf xs).flatMap (insertAll x)

def idxOf (x : Nat) : List Nat → Nat
  | [] => 0
  | y :: ys => if y = x then 0 else idxOf x ys + 1

/-- `mu` is stable iff no unmatched pair (m, w) prefer each other to their
partners. `mu.getD m 0` is m's partner; `idxOf w mu` is w's partner. -/
def isStable (mu : List Nat) : Bool :=
  (List.range 5).all fun m =>
    (List.range 5).all fun w =>
      let wm := mu.getD m 0        -- partner of man m
      let mw := idxOf w mu         -- partner of woman w
      (w = wm) ||
      !(get2 mrank m w < get2 mrank m wm && get2 wrank w m < get2 wrank w mw)

def stableCount : Nat := ((permsOf [0, 1, 2, 3, 4]).filter isStable).length

theorem witness_has_16_stable_matchings : stableCount = 16 := by decide

#print axioms witness_has_16_stable_matchings
"""

out = os.path.join(os.path.dirname(__file__), "Witness.lean")
with open(out, "w") as f:
    f.write(lean)
print(f"wrote {out}")
