/-!
The 5x5 stable-marriage instance found by SAT (see ../../tools/direct_encoding.py) has
exactly 16 stable matchings, verified here by Lean's kernel alone
(`decide`, no imports, no native code).

Rank tables: `mrank[m][w]` = position of woman w in man m's list (0 = most
preferred); `wrank[w][m]` symmetric. Generated by gen_witness.py from the
instance recorded in papers/f5/f5-max-stable-matchings.tex and cross-checked against tools/stable_matchings.py.
-/

def mrank : List (List Nat) := [[2, 0, 1, 4, 3], [1, 3, 4, 2, 0], [2, 4, 3, 0, 1], [4, 1, 0, 2, 3], [0, 2, 3, 4, 1]]
def wrank : List (List Nat) := [[1, 3, 2, 0, 4], [4, 1, 0, 3, 2], [2, 0, 1, 4, 3], [1, 2, 3, 4, 0], [0, 4, 3, 1, 2]]

def get2 (t : List (List Nat)) (i j : Nat) : Nat :=
  ((t.getD i []).getD j 0)

/-- All permutations of a list (each as `mu` with `mu[m]` = partner of m). -/
def insertAll (x : Nat) : List Nat → List (List Nat)
  | [] => [[x]]
  | y :: ys => (x :: y :: ys) :: (insertAll x ys).map (y :: ·)

def permsOf : List Nat → List (List Nat)
  | [] => [[]]
  | x :: xs => (permsOf xs).flatMap (insertAll x)

def idxOf (x : Nat) : List Nat → Nat
  | [] => 0
  | y :: ys => if y = x then 0 else idxOf x ys + 1

/-- `mu` is stable iff no unmatched pair (m, w) prefer each other to their
partners. `mu.getD m 0` is m's partner; `idxOf w mu` is w's partner. -/
def isStable (mu : List Nat) : Bool :=
  (List.range 5).all fun m =>
    (List.range 5).all fun w =>
      let wm := mu.getD m 0        -- partner of man m
      let mw := idxOf w mu         -- partner of woman w
      (w = wm) ||
      !(get2 mrank m w < get2 mrank m wm && get2 wrank w m < get2 wrank w mw)

def stableCount : Nat := ((permsOf [0, 1, 2, 3, 4]).filter isStable).length

theorem witness_has_16_stable_matchings : stableCount = 16 := by decide

#print axioms witness_has_16_stable_matchings
